-- AlterTable
ALTER TABLE `ProjectModule` RENAME COLUMN `rotZ` TO `rotY`,
    ADD COLUMN `posY` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `posX` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `posZ` DOUBLE NOT NULL DEFAULT 0;
